FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    DEBCONF_NONINTERACTIVE_SEEN=true \
    PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install sudo curl python3 python3-pip -y && \
    apt-get clean all
    
RUN ln -sf /usr/bin/python3 /usr/bin/python
    